name: Build tps

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Get kaggle data
        run: kaggle competitions download -c tabular-playground-series-nov-2022
      - name: Process Data
        run: python extract.py
      - name: Run setup script
        run: python main.py
